description: "Develop a data-driven strategy for improving customer retention for a gym chain. This project includes customer segmentation, churn prediction using classification models, and actionable recommendations to enhance retention rates based on behavioral patterns and usage data."
theme: jekyll-theme-cayman
